version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=qubikl_production
      - POSTGRES_USER=qubikl
      - POSTGRES_PASSWORD=qubikl

  web:
    build: .
    command: >
      bash -c "export PATH=/home/qubikl/myapp/bin:$PATH &&
      rm -f tmp/pids/server.pid &&
      bundle exec rails db:create &&
      bundle exec rails db:migrate &&
      bundle exec rails assets:precompile &&
      bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/home/qubikl/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - RACK_ENV=production
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=1
      - QUBIKL_DATABASE_HOST=db
      - QUBIKL_DATABASE_NAME=qubikl_production
      - QUBIKL_DATABASE_USER=qubikl
      - QUBIKL_DATABASE_PASSWORD=qubikl
